version: "3"
services:
  php:
    container_name: d_php
    build:
      context: ./docker/php
      args:
        - UID
      # dockerfile: docker/php/Dockerfile
    working_dir: /usr/local/openresty/nginx/html
    volumes:
      - ../../brander/_aurafit:/usr/local/openresty/nginx/html
      - ./docker/php/zz-docker.conf:/etc/php/5.6/fpm/pool.d/www.conf
      - ./docker/sock:/sock
    links:
      - mysql
      - postfix
    depends_on:
      - mysql
      - postfix
    # network_mode: bridge
  nginx:
    container_name: d_nginx
    build:
      context: ./docker/nginx
      args:
        - UID
    ports:
      - 8003:80
      - 443:443
    volumes:
      - ./:/app/
      - ../../brander/_aurafit/:/usr/local/openresty/nginx/html/
      - ./docker/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./docker/nginx/conf.d/:/usr/local/openresty/nginx/conf/conf.d/
      - ./docker/nginx/log/:/var/log/nginx/
      - ./docker/nginx/ssl/aurafit.key:/root/ssl/aurafit.key
      - ./docker/nginx/ssl/chained.crt:/root/ssl/chained.crt
      - ./lua/:/usr/share/nginx/lua/
      - ./docker/sock/:/sock/
    #volumes_from:
    #  - app
    links:
      - php
    environment:
      NLA_CONFIG_COOKIE_KEY: "change this default key, please"
    depends_on:
      - php
      - mysql
  mysql:
    build:
      context: ./docker/mysql
      #args:
      #  UID: "3000"
    container_name: d_mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/aura.cnf
    ports:
      - 23306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aurafit
      MYSQL_USER: aurafit
      MYSQL_PASSWORD: aurafit
  postfix:
    container_name: d_postfix
    build:
      context: ./docker/postfix
      args:
       - POSTFIX_MYNETWORKS=172.16.0.0/12
       - UID
    volumes:
      - ./docker/postfix/mail:/var/mail
    #ports:
    #  - 25:25
    depends_on:
      - dkim
      # - php
    links:
      - dkim
      #- php
  dkim:
    container_name: d_dkim
    build:
      context: ./docker/dkim
      args:
        - DKIM_DOMAIN=aurafit.com.ua
        - DKIM_SELECTOR=mail
        - DKIM_INTERNAL=127.0.0.1
    expose:
       - 8891
