version: "2"
services:
  app:
    build:
      context: ./docker/php
      # dockerfile: docker/php/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
      - ./html:/usr/share/nginx/html
    expose:
      - 9000
    links:
      - mysql
  nginx:
    image: openresty/openresty
    ports:
      - 8003:80
    volumes:
      - ./:/app
      - ./html:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./docker/nginx/server.conf:/usr/local/openresty/nginx/conf/conf.d/server.conf
      - ./docker/nginx/log:/var/log/nginx
      - ./lua:/usr/share/nginx/lua
      #- ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
    #volumes_from:
    #  - app
    links:
      - app
    environment:
      NLA_CONFIG_COOKIE_KEY: "change this default key, please"
  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
