version: "3"
services:
  app:
    build:
      context: ./docker/php
      args:
        UID: "3000"
      # dockerfile: docker/php/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
      - ./html:/usr/local/openresty/nginx/html
      - ./docker/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./docker/sock:/sock
    expose:
      - 9000
    links:
      - mysql
  nginx:
    build:
      context: ./docker/nginx
      args:
        UID: "3000"
    ports:
      - 8003:80
    volumes:
      - ./:/app/
      - ./html/:/usr/local/openresty/nginx/html/
      - ./docker/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./docker/nginx/conf.d/:/usr/local/openresty/nginx/conf/conf.d/
      - ./docker/nginx/log/:/var/log/nginx/
      - ./lua/:/usr/share/nginx/lua/
      - ./docker/sock/:/sock/
    #volumes_from:
    #  - app
    links:
      - app
      - mysql
    environment:
      NLA_CONFIG_COOKIE_KEY: "change this default key, please"
    depends_on:
      - app
  mysql:
    image:  mysql:5.7
    #build:
    #  context: ./docker/mysql
    #  args:
    #    UID: "3000"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
  mongodb:
    image: mongo:3.6
    #build:
    #  context: ./docker/mongodb
    #  args:
    #    UID: "3000"
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongodb/data/configdb:/data/configdb
      - ./docker/mongodb/data/db:/data/db
